# Generated by Django 4.1.7 on 2023-03-17 01:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name': 'day',
                'verbose_name_plural': 'days',
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.CharField(error_messages={'unique': 'This week number already exists'}, max_length=2, unique=True)),
            ],
            options={
                'verbose_name': 'week',
                'verbose_name_plural': 'weeks',
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('sets', models.CharField(blank=True, max_length=2, null=True)),
                ('reps', models.CharField(blank=True, max_length=10, null=True)),
                ('percentage', models.IntegerField(blank=True, null=True)),
                ('day', models.ForeignKey(default='1.1', on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='workout_app.day')),
                ('week', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='workout_app.week')),
            ],
            options={
                'verbose_name': 'workout',
                'verbose_name_plural': 'workouts',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weights', models.IntegerField(choices=[(1, 'LB'), (2, 'KG')], default=1)),
                ('max_snatch', models.IntegerField(null=True)),
                ('max_cleanjerk', models.IntegerField(null=True)),
                ('max_frontsquat', models.IntegerField(null=True)),
                ('max_backsquat', models.IntegerField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='day',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='workout_app.week'),
        ),
    ]
