# Generated by Django 4.1.7 on 2023-04-04 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0002_alter_workout_day_alter_workout_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='percentage',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
