# Generated by Django 4.1.7 on 2023-04-06 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0003_alter_workout_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='max_backsquat',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='max_cleanjerk',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='max_frontsquat',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='max_snatch',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
